<a href="https://colab.research.google.com/github/won195/TIL/blob/master/broadcasting%EA%B3%BC_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
a1 = [[1,2,3], [4,5,6,], [7,8,9]]
df1 = pd.DataFrame(a1, columns=list("ABC"), index=list("가나다"))
df2 = df1.reindex(columns=list("BCA"), index=list("나다가")).copy()
sr1 = df1.loc["가"]
df3 = df1.iloc[:2,:2]
df1

   A  B  C
가  1  2  3
나  4  5  6
다  7  8  9

In [4]:
df1 * df1

    A   B   C
가   1   4   9
나  16  25  36
다  49  64  81

In [5]:
df1 + df2

    A   B   C
가   2   4   6
나   8  10  12
다  14  16  18

In [6]:
df1 + df3

     A     B   C
가  2.0   4.0 NaN
나  8.0  10.0 NaN
다  NaN   NaN NaN

In [7]:
df1.add(df3, fill_value=0)

     A     B    C
가  2.0   4.0  3.0
나  8.0  10.0  6.0
다  7.0   8.0  9.0

In [11]:
df1 + sr1

   A   B   C
가  2   4   6
나  5   7   9
다  8  10  12

In [9]:
df1.add(sr1, axis=1)

   A   B   C
가  2   4   6
나  5   7   9
다  8  10  12