<a href="https://colab.research.google.com/github/won195/TIL/blob/master/%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%85%98_%5B%EB%A7%A4%EC%9D%BC10%EB%B6%84_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D%5D_%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%9C%BC%EB%A1%9C_SQL_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0_1%ED%83%84_(Jupyter_Notebook_DataBase_sqlite).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Base
  * 정형데이터 -> 관계형 데이터 베이스 관리 시스템(RDB)
  * 여러가지 테이블 존재
    - 마스터 데이터
    - 로그 데이터
    - 설명 데이터

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
connection = sqlite3.connect("/content/drive/MyDrive/데이터스테이션/data/chinook.db")

In [ ]:
query = "SELECT * FROM sqlite_master;"

In [ ]:
datavase_table = pd.read_sql_query(query, connection)
datavase_table["sql"]

0     CREATE TABLE "albums"\r\n(\r\n    [AlbumId] IN...
1                CREATE TABLE sqlite_sequence(name,seq)
2     CREATE TABLE "artists"\r\n(\r\n    [ArtistId] ...
3     CREATE TABLE "customers"\r\n(\r\n    [Customer...
4     CREATE TABLE "employees"\r\n(\r\n    [Employee...
5     CREATE TABLE "genres"\r\n(\r\n    [GenreId] IN...
6     CREATE TABLE "invoices"\r\n(\r\n    [InvoiceId...
7     CREATE TABLE "invoice_items"\r\n(\r\n    [Invo...
8     CREATE TABLE "media_types"\r\n(\r\n    [MediaT...
9     CREATE TABLE "playlists"\r\n(\r\n    [Playlist...
10    CREATE TABLE "playlist_track"\r\n(\r\n    [Pla...
11                                                 None
12    CREATE TABLE "tracks"\r\n(\r\n    [TrackId] IN...
13    CREATE INDEX [IFK_AlbumArtistId] ON "albums" (...
14    CREATE INDEX [IFK_CustomerSupportRepId] ON "cu...
15    CREATE INDEX [IFK_EmployeeReportsTo] ON "emplo...
16    CREATE INDEX [IFK_InvoiceCustomerId] ON "invoi...
17    CREATE INDEX [IFK_InvoiceLineInvoiceId] ON "in...
18    CREATE INDEX [IFK_InvoiceLineTrackId] ON "invo...
19    CREATE INDEX [IFK_PlaylistTrackTrackId] ON "pl...
20    CREATE INDEX [IFK_TrackAlbumId] ON "tracks" ([...
21    CREATE INDEX [IFK_TrackGenreId] ON "tracks" ([...
22    CREATE INDEX [IFK_TrackMediaTypeId] ON "tracks...
23              CREATE TABLE sqlite_stat1(tbl,idx,stat)
24    CREATE TABLE Test (\nidx integer prinary key\n...
Name: sql, dtype: object

In [ ]:
query = "SELECT * FROM 'customers'"
df_customers = pd.read_sql_query(query, connection)
df_customers.shape

(59, 13)

In [ ]:
df_customers.head(2)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5

In [ ]:
# df_customers.to_excel("customer_file.xlsx")

In [ ]:
query = "SELECT * FROM 'invoices'"
df_invoices = pd.read_sql_query(query, connection)
df_invoices.shape

(412, 9)

In [ ]:
cond1 = (df_invoices["BillingCountry"] == 'Germany')
df_invoices.loc[cond1]

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
5,6,37,2009-01-19 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,0.99
6,7,38,2009-02-01 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
11,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
28,29,36,2009-05-05 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
29,30,38,2009-05-06 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,3.96
39,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
51,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
66,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91
94,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
103,104,38,2010-03-29 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,0.99
126,127,37,2010-07-13 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,1.98
137,138,37,2010-08-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,13.86
192,193,37,2011-04-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,14.91
195,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
218,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96
223,224,36,2011-09-20 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
224,225,38,2011-09-20 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
235,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
240,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94
246,247,36,2011-12-23 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,3.96
268,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
290,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
292,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99
320,321,36,2012-11-14 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,0.99
321,322,37,2012-11-27 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,1.98
344,345,37,2013-03-01 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,3.96
366,367,37,2013-06-03 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,5.94

In [ ]:
query = "SELECT * FROM 'invoices' WHERE BillingCountry='Germany' "
df_invoices = pd.read_sql_query(query, connection)
df_invoices.shape

(28, 9)